apiVersion: apps/v1
kind: Deployment
metadata:
  name:  expense-app-deployment
spec:
  selector:
    matchLabels:
      app: expense-app
  replicas: 2
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      containers:
        - name: expense-app
          image: prakashnb/myimages:tag123
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: expense-app-service
spec:
  selector:
    app: expense-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort